AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  AllowedMethods: ["describe", "context"]
Style/Documentation:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
